[ SMS_Report (TRUE),
  SMS_Group_Name ("TEAL Device Guard"),
  SMS_Class_ID ("TEAL|DEVICE_GUARD|1.0"),
  Namespace ("\\\\\\\\.\\\\root\\\\Microsoft\\\\Windows\\\\DeviceGuard") ]
class Win32_DeviceGuard : SMS_Class_Template
{
    [ SMS_Report (TRUE), key ]
    String     InstanceIdentifier;
    [ SMS_Report (TRUE) ]
    UInt32     AvailableSecurityProperties;
    [ SMS_Report (TRUE) ]
    UInt32     CodeIntegrityPolicyEnforcementStatus;
    [ SMS_Report (TRUE) ]
    UInt32     RequiredSecurityProperties;
    [ SMS_Report (TRUE) ]
    UInt32     SecurityServicesConfigured;
    [ SMS_Report (TRUE) ]
    UInt32     SecurityServicesRunning;
    [ SMS_Report (TRUE) ]
    UInt32     UsermodeCodeIntegrityPolicyEnforcementStatus;
    [ SMS_Report (TRUE) ]
    String     Version;
    [ SMS_Report (TRUE) ]
    UInt32     VirtualizationBasedSecurityStatus;
};

[ SMS_Report (TRUE),
  SMS_Group_Name ("Win32Reg_CredentialGuard"),
  SMS_Class_ID ("MICROSOFT|WIN32REG_CREDENTIALGUARD|1.0"),
  Namespace ("root\\\\cimv2") ]
class Win32Reg_CredentialGuard : SMS_Class_Template
{
    [ SMS_Report (TRUE), key ]
    String     InstanceKey;
    [ SMS_Report (TRUE) ]
    UInt32     EnableVirtualizationBasedSecurity;
    [ SMS_Report (TRUE) ]
    UInt32     LsaCfgFlags;
    [ SMS_Report (TRUE) ]
    UInt32     RequirePlatformSecurityFeatures;
};

