
//==================================================================
// Define registry classes for inventory reporting
//
// - Registry key/value class definition should be done in cimv2,
// - SMS class definition should be done in cimv2\\sms
//==================================================================

//==================================================================
// Define registry classes for reporting on Credential Guard configuration
//==================================================================

//----------------------
// Credential Guard
//----------------------

#pragma namespace ("\\\\.\\root\\cimv2")

[DYNPROPS]
class Win32Reg_CredentialGuard
{
    [key]
        string InstanceKey;
        uint32 LsaCfgFlags;
        uint32 EnableVirtualizationBasedSecurity;
        uint32 RequirePlatformSecurityFeatures;
};

[DYNPROPS]
instance of Win32Reg_CredentialGuard
{
    InstanceKey = "CredentialGuardKey";
    [PropertyContext("local|HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\Lsa|LsaCfgFlags"),
                    Dynamic, Provider("RegPropProv")]
        LsaCfgFlags;
    [PropertyContext("local|HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\DeviceGuard|EnableVirtualizationBasedSecurity"),
                    Dynamic, Provider("RegPropProv")]
        EnableVirtualizationBasedSecurity;
    [PropertyContext("local|HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\DeviceGuard|RequirePlatformSecurityFeatures"),
                    Dynamic, Provider("RegPropProv")]
        RequirePlatformSecurityFeatures;
};
